Repository FACK1/M-E-Platform, pull requests merged in 2019-02, with the labels that each got.

#52 Add table to one activity information page #2 fixed #51
  client/src/components/pages/ActivityInformation/index.js
  client/src/components/pages/ActivityInformation/index.style.js
Labels: awaiting-review

#47 add new user to database, make endpoint to add, BackEnd fixed #44
  client/src/App.js
  client/src/components/Header/index.js
  client/src/components/pages/CreateStudent/index.css
  client/src/components/pages/CreateStudent/index.js
  client/src/components/pages/CreateUser/index.js
  client/src/components/pages/CreateUser/index.style.js
  client/src/components/pages/ViewStudents/index.css
  client/src/components/pages/ViewStudents/index.js
  client/src/components/pages/ViewUsers/index.js
  client/src/components/pages/ViewUsers/index.style.js
  src/controllers/index.js
  src/controllers/user.controller.js
  src/models/User.js
  src/router.js
Labels: awaiting-review

#48 Add program
  client/src/App.js
  client/src/components/pages/CreateProgram/index.css
  client/src/components/pages/CreateProgram/index.js
  client/src/components/pages/CreateProgram/index.style.js
  package-lock.json
  package.json
  src/controllers/index.js
  src/controllers/program.controller.js
  src/router.js
Labels: awaiting-review

#59 View users #7 fixed #57
  client/src/components/pages/ViewUsers/index.js
  src/controllers/user.controller.js
  src/router.js
Labels: in-review

#60 Activity details
  client/package-lock.json
  client/package.json
  client/src/components/pages/ViewActivities/index.js
  package-lock.json
  package.json
Labels: in-review

#56 View programs
  client/src/App.js
  client/src/components/Header/index.js
  client/src/components/pages/ViewPrograms/index.css
  client/src/components/pages/ViewPrograms/index.js
  client/src/components/pages/ViewPrograms/index.style.js
  src/controllers/activity.controller.js
  src/controllers/program.controller.js
  src/router.js
Labels: in-review

#66 Program information
  client/src/App.js
  client/src/components/ProgramDetails/index.js
  client/src/components/ProgramDetails/index.style.js
  client/src/components/pages/ProgramInformation/index.js
  client/src/components/pages/ProgramInformation/index.style.js
  src/controllers/program.controller.js
  src/router.js
Labels: awaiting-review

#70 Heroku
  package.json
Labels: in-review

#71 fix program and objective in add activity #10
  client/package-lock.json
  client/src/components/pages/CreateActivity/index.js
  src/controllers/index.js
  src/controllers/objective.controller.js
  src/router.js
Labels: in-review

#62 Add user to activity #12 fixed #58
  client/src/components/pages/ActivityInformation/index.js
  src/controllers/activity.controller.js
  src/controllers/user.controller.js
  src/models/ActivitiesUser.js
  src/mongoose.config.js
  src/router.js
Labels: in-review

#81 Server validation
  package-lock.json
  package.json
  src/router.js
  src/validations/checkUser.validation.js
  src/validations/index.js
  src/validations/user.validate.js
  src/validations/validation.js
Labels: in-review

#82 Form initial values
  client/src/components/Form/index.js
  client/src/components/pages/CreateActivity/index.js
Labels: in-review

#92 Show activity users
  client/src/components/pages/ActivityInformation/index.js
  src/controllers/activity.controller.js
  src/controllers/user.controller.js
  src/models/ActivitiesUser.js
  src/router.js
Labels: bug, in-review, technical

#90 Fix buttons response
  client/src/components/Form/index.js
  client/src/components/Form/index.style.js
  client/src/components/pages/CreateActivity/index.js
  client/src/components/pages/CreateProgram/index.js
  client/src/components/pages/CreateUser/index.js
  src/controllers/user.controller.js
  src/validations/user.validate.js
Labels: bug, in-review, technical

#84 Server Authentication
  package-lock.json
  package.json
  src/controllers/auth.controller.js
  src/controllers/index.js
  src/models/User.js
  src/router.js
Labels: in-review, technical

#95 Fix activity multi add fixed #93 #94
  client/src/components/pages/ActivityInformation/index.js
  src/controllers/auth.controller.js
  src/controllers/user.controller.js
  src/models/ActivitiesUser.js
  src/models/User.js
  src/router.js
Labels: awaiting-review, bug, technical

#103 Modify pages title to make it consistant #102
  client/src/components/pages/ActivityInformation/index.style.js
  client/src/components/pages/ProgramInformation/index.style.js
  client/src/components/pages/ViewActivities/index.style.js
  client/src/components/pages/ViewPrograms/index.style.js
  client/src/components/pages/ViewUsers/index.style.js
Labels: awaiting-review, bug, done

#101 Update the title of the app #100
  client/public/index.html
Labels: awaiting-review, done
